[project]
name = "AudioTools"
version = "0.2.0"
description = ""
authors = ["IX <borntokill.ix@gmail.com>"]
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "audioop-lts>=0.2.1",
    "boto3>=1.38.20",
    "fastapi>=0.115.12",
    "multipart>=1.2.1",
    "pydantic-settings>=2.9.1",
    "pydub>=0.25.1",
    "pyjwt>=2.10.1",
    "python-multipart>=0.0.20",
    "torch>=2.7.0",
    "torchaudio>=2.7.0",
    "transformers>=4.52.1",
    "uvicorn>=0.34.2",
]

[tool.commitizen]
name = "cz_conventional_commits"
tag_format = "$version"
version_scheme = "semver2"
version_provider = "pep621"
update_changelog_on_bump = true
# major_version_zero = true

[dependency-groups]
dev = ["pytest"]
lint = ["ruff"]

[tool.ruff.lint]
dummy-variable-rgx = "^_$"

[tool.ruff.lint.flake8-quotes]
docstring-quotes = "double"
inline-quotes = "single"

[tool.ruff.lint.isort]
split-on-trailing-comma=true
combine-as-imports=true
known-third-party = ["bound"]

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F401", "PLC0414"]
"examples/**" = ["N805", "N999", "RUF012"]
"tests/**" = ["RUF012", "SIM115"]
